[package]
name = "sys-voice-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
sys-voice = { path = ".." }
tokio = { version = "1", features = ["rt-multi-thread"] }
