[package]
name = "sys-voice-android-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sys-voice = { path = ".." }
jni = "0.21"
tokio = { version = "1", features = ["rt-multi-thread"] }
android_logger = "0.14"
log = "0.4"
